version: '3.3' 
services:
  docker-eclipse-oxygen:
    image: openkbs/netbeans-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netbeans-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=${DISPLAY:-":0.0"}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .netbeans:/home/developer/.netbeans

